const fs = require('fs');
const data = JSON.parse(fs.readFileSync('C:/Users/yaniv/name-that-artist/artists.json', 'utf8'));

const typeMap = {
  // Bands/Groups
  "The Beatles": "band",
  "The Rolling Stones": "band",
  "Led Zeppelin": "band",
  "The Doors": "band",
  "Pink Floyd": "band",
  "Queen": "band",
  "Fleetwood Mac": "band",
  "Eagles": "band",
  "The Police": "band",
  "Bon Jovi": "band",
  "U2": "band",
  "AC/DC": "band",
  "Simon & Garfunkel": "band",
  "The Beach Boys": "band",
  "Nirvana": "band",
  "Oasis": "band",
  "Radiohead": "band",
  "Green Day": "band",
  "Foo Fighters": "band",
  "Red Hot Chili Peppers": "band",
  "Arctic Monkeys": "band",
  "Coldplay": "band",
  "Gorillaz": "band",
  "Twenty One Pilots": "band",
  "Imagine Dragons": "band",
  "Metallica": "band",
  "Guns N' Roses": "band",
  "Def Leppard": "band",
  "Linkin Park": "band",
  "Black Sabbath": "band",
  "ABBA": "band",
  "Duran Duran": "band",
  "Destiny's Child": "band",
  "The Black Eyed Peas": "band",
  "Daft Punk": "band",
  "Depeche Mode": "band",
  "The Chainsmokers": "band",
  "Swedish House Mafia": "band",
  "Iron Maiden": "band",
  "Slipknot": "band",
  "The Strokes": "band",
  "Vampire Weekend": "band",
  "Glass Animals": "band",
  "The 1975": "band",
  "The Who": "band",
  "The Kinks": "band",
  "The Supremes": "band",
  "The Temptations": "band",
  "Bee Gees": "band",
  "Lynyrd Skynyrd": "band",
  "Blondie": "band",
  "Dire Straits": "band",
  "The Ramones": "band",
  "The Clash": "band",
  "Genesis": "band",
  "Creedence Clearwater Revival": "band",
  "Aerosmith": "band",
  "ZZ Top": "band",
  "Journey": "band",
  "Foreigner": "band",
  "Heart": "band",
  "Hall & Oates": "band",
  "The Cure": "band",
  "New Order": "band",
  "Tears for Fears": "band",
  "Eurythmics": "band",
  "A-ha": "band",
  "Wham!": "band",
  "Culture Club": "band",
  "Van Halen": "band",
  "Motley Crue": "band",
  "Mötley Crüe": "band",
  "R.E.M.": "band",
  "Talking Heads": "band",
  "The Smiths": "band",
  "Pet Shop Boys": "band",
  "The Human League": "band",
  "Beastie Boys": "band",
  "Public Enemy": "band",
  "Run-DMC": "band",
  "Salt-N-Pepa": "band",
  "Backstreet Boys": "band",
  "NSYNC": "band",
  "Spice Girls": "band",
  "Pearl Jam": "band",
  "Soundgarden": "band",
  "Alice in Chains": "band",
  "Stone Temple Pilots": "band",
  "Blur": "band",
  "Pulp": "band",
  "Weezer": "band",
  "Garbage": "band",
  "Portishead": "band",
  "Massive Attack": "band",
  "Smashing Pumpkins": "band",
  "Nine Inch Nails": "band",
  "Blink-182": "band",
  "Wu-Tang Clan": "band",
  "A Tribe Called Quest": "band",
  "Outkast": "band",
  "Fugees": "band",
  "TLC": "band",
  "Boyz II Men": "band",
  "My Chemical Romance": "band",
  "Fall Out Boy": "band",
  "Paramore": "band",
  "Panic! at the Disco": "band",
  "The Killers": "band",
  "Franz Ferdinand": "band",
  "Arcade Fire": "band",
  "Interpol": "band",
  "Nickelback": "band",
  "Kings of Leon": "band",
  "Snow Patrol": "band",
  "Keane": "band",
  "The White Stripes": "band",
  "The Black Keys": "band",
  "Muse": "band",
  "Queens of the Stone Age": "band",
  "Modest Mouse": "band",
  "Death Cab for Cutie": "band",
  "BTS": "band",
  "BLACKPINK": "band",
  "Mumford & Sons": "band",
  "Florence + the Machine": "band",
  "Bastille": "band",
  "Alt-J": "band",
  "Of Monsters and Men": "band",
  "Cage the Elephant": "band",
  "MGMT": "band",
  "The National": "band",
  "The Script": "band",
  "Bon Iver": "band",
  "Fleet Foxes": "band",
  "Pantera": "band",
  "System of a Down": "band",
  "Tool": "band",
  "Rammstein": "band",
  "Korn": "band",
  "Kraftwerk": "band",
  "The Chemical Brothers": "band",
  "The Prodigy": "band",
  "Santana": "band",
  "Evanescence": "band",
  "Tame Impala": "solo_male",
  // Solo Male
  "Jimi Hendrix": "solo_male",
  "David Bowie": "solo_male",
  "Elton John": "solo_male",
  "Bruce Springsteen": "solo_male",
  "Tom Petty": "solo_male",
  "Bob Dylan": "solo_male",
  "Michael Jackson": "solo_male",
  "Prince": "solo_male",
  "George Michael": "solo_male",
  "Justin Timberlake": "solo_male",
  "Ed Sheeran": "solo_male",
  "Bruno Mars": "solo_male",
  "Harry Styles": "solo_male",
  "Justin Bieber": "solo_male",
  "Eminem": "solo_male",
  "2Pac": "solo_male",
  "The Notorious B.I.G.": "solo_male",
  "Jay-Z": "solo_male",
  "Kanye West": "solo_male",
  "Drake": "solo_male",
  "Kendrick Lamar": "solo_male",
  "Post Malone": "solo_male",
  "Tyler the Creator": "solo_male",
  "Lil Nas X": "solo_male",
  "50 Cent": "solo_male",
  "Childish Gambino": "solo_male",
  "Marvin Gaye": "solo_male",
  "Stevie Wonder": "solo_male",
  "Bob Marley": "solo_male",
  "Usher": "solo_male",
  "Frank Ocean": "solo_male",
  "John Legend": "solo_male",
  "Sam Smith": "solo_male",
  "Khalid": "solo_male",
  "Anderson .Paak": "solo_male",
  "The Weeknd": "solo_male",
  "Calvin Harris": "solo_male",
  "Avicii": "solo_male",
  "Johnny Cash": "solo_male",
  "Garth Brooks": "solo_male",
  "Willie Nelson": "solo_male",
  "Morgan Wallen": "solo_male",
  "Chris Stapleton": "solo_male",
  "Bad Bunny": "solo_male",
  "J Balvin": "solo_male",
  "Nelly": "solo_male",
  "Ozzy Osbourne": "solo_male",
  "Skrillex": "solo_male",
  "Marshmello": "solo_male",
  "Enrique Iglesias": "solo_male",
  "Ozuna": "solo_male",
  "Moby": "solo_male",
  "Fatboy Slim": "solo_male",
  "Luke Combs": "solo_male",
  "Zach Bryan": "solo_male",
  "Kenny Rogers": "solo_male",
  "Tim McGraw": "solo_male",
  "Brad Paisley": "solo_male",
  "Blake Shelton": "solo_male",
  "Luke Bryan": "solo_male",
  "Keith Urban": "solo_male",
  "Alan Jackson": "solo_male",
  "Daddy Yankee": "solo_male",
  "Marc Anthony": "solo_male",
  "Ricky Martin": "solo_male",
  "Pitbull": "solo_male",
  "Maluma": "solo_male",
  "Lil Baby": "solo_male",
  "Juice WRLD": "solo_male",
  "Jack Harlow": "solo_male",
  "Giveon": "solo_male",
  "Noah Kahan": "solo_male",
  "Benson Boone": "solo_male",
  "Rod Wave": "solo_male",
  "Gunna": "solo_male",
  "Polo G": "solo_male",
  "Feid": "solo_male",
  "Rauw Alejandro": "solo_male",
  "Beck": "solo_male",
  "Nas": "solo_male",
  "DMX": "solo_male",
  "Snoop Dogg": "solo_male",
  "Lil Wayne": "solo_male",
  "T.I.": "solo_male",
  "Chris Brown": "solo_male",
  "John Mayer": "solo_male",
  "Hozier": "solo_male",
  "Lewis Capaldi": "solo_male",
  "Passenger": "solo_male",
  "David Guetta": "solo_male",
  "Tiësto": "solo_male",
  "Zedd": "solo_male",
  "Travis Scott": "solo_male",
  "Future": "solo_male",
  "J. Cole": "solo_male",
  "Macklemore": "solo_male",
  "Ne-Yo": "solo_male",
  "Phil Collins": "solo_male",
  "Neil Young": "solo_male",
  "Cat Stevens": "solo_male",
  "Van Morrison": "solo_male",
  "Billy Joel": "solo_male",
  "James Brown": "solo_male",
  "Ray Charles": "solo_male",
  "Sam Cooke": "solo_male",
  "Otis Redding": "solo_male",
  "Peter Gabriel": "solo_male",
  "Rick Astley": "solo_male",
  // Additional artists
  "Dolly Parton": "solo_female",
  "Missy Elliott": "solo_female",
  "Brandy": "solo_female",
  "Maroon 5": "band",
  "OneRepublic": "band",
  "Peso Pluma": "solo_male",
  // Solo Female
  "P!nk": "solo_female",
  "Alanis Morissette": "solo_female",
  "Lorde": "solo_female",
  "Lana Del Rey": "solo_female",
  "Madonna": "solo_female",
  "Whitney Houston": "solo_female",
  "Mariah Carey": "solo_female",
  "Cyndi Lauper": "solo_female",
  "Taylor Swift": "solo_female",
  "Katy Perry": "solo_female",
  "Lady Gaga": "solo_female",
  "Rihanna": "solo_female",
  "Beyoncé": "solo_female",
  "Adele": "solo_female",
  "Ariana Grande": "solo_female",
  "Dua Lipa": "solo_female",
  "Billie Eilish": "solo_female",
  "Olivia Rodrigo": "solo_female",
  "Sabrina Carpenter": "solo_female",
  "Selena Gomez": "solo_female",
  "Nicki Minaj": "solo_female",
  "Cardi B": "solo_female",
  "Doja Cat": "solo_female",
  "Lauryn Hill": "solo_female",
  "Aretha Franklin": "solo_female",
  "Alicia Keys": "solo_female",
  "Amy Winehouse": "solo_female",
  "SZA": "solo_female",
  "Donna Summer": "solo_female",
  "Shania Twain": "solo_female",
  "Shakira": "solo_female",
  "Rosalía": "solo_female",
  "Karol G": "solo_female",
  "Carrie Underwood": "solo_female",
  "Halsey": "solo_female",
  "Sia": "solo_female",
  "Lizzo": "solo_female",
  "Camila Cabello": "solo_female",
  "Megan Thee Stallion": "solo_female",
  "Norah Jones": "solo_female",
  "Nelly Furtado": "solo_female",
  "Avril Lavigne": "solo_female",
  "Stevie Nicks": "solo_female",
  "Joni Mitchell": "solo_female",
  "Janet Jackson": "solo_female",
  "Tina Turner": "solo_female",
  // Israeli artists
  "\u05D0\u05E8\u05D9\u05E7 \u05D0\u05D9\u05D9\u05E0\u05E9\u05D8\u05D9\u05D9\u05DF": "solo_male",
  "\u05E9\u05DC\u05DE\u05D4 \u05D0\u05E8\u05E6\u05D9": "solo_male",
  "\u05DB\u05D5\u05D5\u05E8\u05EA": "band",
  "\u05E9\u05DC\u05D5\u05DD \u05D7\u05E0\u05D5\u05DA": "solo_male",
  "\u05D9\u05D4\u05D5\u05D3\u05D9\u05EA \u05E8\u05D1\u05D9\u05E5": "solo_female",
  "\u05DE\u05EA\u05D9 \u05DB\u05E1\u05E4\u05D9": "solo_male",
  "\u05D7\u05D5\u05D4 \u05D0\u05DC\u05D1\u05E8\u05E9\u05D8\u05D9\u05D9\u05DF": "solo_female",
  "\u05D0\u05D4\u05D5\u05D3 \u05D1\u05E0\u05D0\u05D9": "solo_male",
  "\u05D2\u05D9\u05D3\u05D9 \u05D2\u05D5\u05D1": "solo_male",
  "\u05D9\u05D4\u05D5\u05E8\u05DD \u05D2\u05D0\u05D5\u05DF": "solo_male",
  "\u05E2\u05D1\u05E8\u05D9 \u05DC\u05D9\u05D3\u05E8": "solo_male",
  "\u05D0\u05D1\u05D9\u05D1 \u05D2\u05E4\u05DF": "solo_male",
  "\u05E8\u05D9\u05D8\u05D4": "solo_female",
  "\u05D3\u05E0\u05D4 \u05D0\u05D9\u05E0\u05D8\u05E8\u05E0\u05E9\u05D9\u05D5\u05E0\u05DC": "solo_female",
  "\u05DE\u05E9\u05D9\u05E0\u05D4": "band",
  "\u05D0\u05EA\u05E0\u05D9\u05E7\u05E1": "band",
  "\u05DB\u05E0\u05E1\u05D9\u05D9\u05EA \u05D4\u05E9\u05DB\u05DC": "band",
  "\u05D4\u05D9\u05D4\u05D5\u05D3\u05D9\u05DD": "band",
  "\u05D8\u05D9\u05E4\u05E7\u05E1": "band",
  "\u05E9\u05D1\"\u05E7 \u05E1'": "band",
  "\u05DE\u05D5\u05E0\u05D9\u05E7\u05D4 \u05E1\u05E7\u05E1": "band",
  "\u05D6\u05D4\u05D1\u05D4 \u05D1\u05DF": "solo_female",
  "\u05E9\u05E8\u05D9\u05EA \u05D7\u05D3\u05D3": "solo_female",
  "\u05E7\u05D5\u05D1\u05D9 \u05E4\u05E8\u05E5": "solo_male",
  "\u05E2\u05D9\u05D3\u05DF \u05E8\u05D9\u05D9\u05DB\u05DC": "solo_male",
  "\u05E0\u05D5\u05E2\u05D4 \u05E7\u05D9\u05E8\u05DC": "solo_female",
  "\u05D0\u05D5\u05DE\u05E8 \u05D0\u05D3\u05DD": "solo_male",
  "\u05E2\u05D3\u05DF \u05D1\u05DF \u05D6\u05E7\u05DF": "solo_female",
  "\u05E1\u05D8\u05D8\u05D9\u05E7 \u05D5\u05D1\u05DF \u05D0\u05DC \u05EA\u05D1\u05D5\u05E8\u05D9": "band",
  "\u05D9\u05E9\u05D9 \u05E8\u05D9\u05D1\u05D5": "solo_male",
};

let missing = [];
data.artists.forEach(a => {
  if (typeMap[a.name]) {
    a.type = typeMap[a.name];
  } else {
    missing.push(a.name);
  }
});

if (missing.length > 0) {
  console.log('MISSING TYPE FOR:', JSON.stringify(missing, null, 2));
} else {
  console.log('All artists have types!');
  fs.writeFileSync('C:/Users/yaniv/name-that-artist/artists.json', JSON.stringify(data, null, 2));
  console.log('artists.json updated with', data.artists.length, 'artists.');
}
